/**
 * @description Represents the payload for a contact email.
 * @export
 * @interface ContactEmailProps
 * @property {string} name - The sender's full name.
 * @property {string} email - The sender's email address (from the contact form).
 * @property {string} phone - The sender's phone number (from the contact form).
 * @property {string} description - The message or description provided by the sender.
 * @property {string} [honeypot] - Hidden anti-bot field; legitimate clients always leave it empty.
 */
export interface ContactEmailProps {
  name: string
  email: string
  phone: string
  description: string
  honeypot?: string
}

/**
 * @description Represents the structure of an error object returned by AWS SDK operations.
 * @export
 * @interface AwsSdkErrorProps
 * @property {string} [name] - The name of the error.
 * @property {string} [message] - A descriptive message about the error.
 * @property {string} [code] - The error code returned by AWS SDK.
 * @property {number} [errno] - The error number, if applicable.
 * @property {string} [syscall] - The system call that triggered the error, if applicable.
 * @property {string} [hostname] - The hostname involved in the error, if applicable.
 * @property {object} [$metadata] - Additional metadata about the AWS SDK request and response.
 * @property {number} [$metadata.httpStatusCode] - The HTTP status code returned by AWS.
 * @property {string} [$metadata.requestId] - The unique request ID generated by AWS for this operation.
 * @property {number} [$metadata.attempts] - The number of retry attempts made by the AWS SDK for this operation.
 * @property {number} [$metadata.totalRetryDelay] - The total delay in milliseconds caused by retries for this operation.
 */
export interface AwsSdkErrorProps {
  name?: string
  message?: string
  code?: string
  errno?: number
  syscall?: string
  hostname?: string
  $metadata?: {
    httpStatusCode?: number
    requestId?: string
    attempts?: number
    totalRetryDelay?: number
  }
}
